---
site:
  title: OCP Multi-user Solve/Validate — Reference Lab
  url: https://rhpds.github.io/ocp-zt-tenant-showroom
  start_page: modules::index.adoc

content:
  sources:
    - url: .
      start_path: content

ui:
  bundle:
    url: https://github.com/rhpds/rhdp_showroom_theme/releases/download/rh-one-2025/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ./content/supplemental-ui
    - path: ./content/lib
    - path: .nojekyll
    - path: ui.yml
      contents: "static_files: [ .nojekyll, css/site-extra.css, js/buttons.js ]"

runtime:
  cache_dir: ./.cache/antora

antora:
  extensions:
    - require: ./content/lib/dev-mode.js
      enabled: false

output:
  dir: ./www
