---
type: showroom

default_width: 35
persist_url_state: true

tabs:
  - name: OCP Console
    url: 'https://console-openshift-console.${DOMAIN}'
    external: false
  - name: Terminal
    url: /wetty
    type: terminal
