---
type: showroom

default_width: 35
persist_url_state: true

antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: "Welcome & How It Works"
    - name: module-01
      label: "Module 1: ConfigMap in Namespace"
    - name: module-02
      label: "Module 2: Secret in Second Namespace"
    - name: module-e2e
      label: "E2E Load Testing"
    - name: conclusion
      label: "Developer Guide"

tabs:
  - name: OCP Console
    url: 'https://console-openshift-console.${DOMAIN}'
    external: false

skipModuleEnabled: true
