FROM quay.io/rhpds/zerotouch-automation:v1.2.0

USER root

RUN pip install --no-cache-dir kubernetes && \
    ansible-galaxy collection install kubernetes.core && \
    chmod -R g+rwX /opt/app-root/src/.ansible && \
    chown -R 1001:0 /opt/app-root/src/.ansible

USER 1001
